// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // CLI operations (migrate/studio/db push) need a direct, non-pooled connection.
  // The running app uses DATABASE_URL (pooled) via a driver adapter — see src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
